### ISSUE TITLE
W1b: no `generator=` anywhere, and `forward` silently swallows it with every other unknown kwarg

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#4427]
Every augmentation in `kornia.augmentation` draws from the global `torch` RNG. `torch.manual_seed` reproduces any class's draw, which is enough for a single-threaded script and not enough for anything that wants isolated streams — a `DataLoader` worker, two pipelines that must not perturb each other, or a test that seeds once and then calls an unrelated `torch.rand`. `torch` answers this with a per-call `generator=` argument, and `kornia.augmentation` has no equivalent: no constructor and no container accepts `generator=`.

The second half is the part a caller cannot see. `forward` accepts `generator=` without complaint and drops it — the keyword is swallowed by the unknown-kwarg path that feeds `override_parameters`, so the call returns a normal result drawn from the global stream. Passing two different generators produces bitwise-identical output. The same path swallows any other misspelled or invented keyword, including a bogus key inside `extra_args`, so a typo in a keyword argument is indistinguishable from a correct call.

What a caller is left with is the global stream, and how much of it each augmentation consumes is not uniform: a class with a static `p` of `0.0` or `1.0` skips the gate draw entirely, while a class with a `_param_generator` draws its parameters regardless of `p`. So `p=0.0` is not a guarantee that an augmentation leaves the stream alone, and a chain's consumption depends on which classes are in it.

## Repro

```python
import torch
import kornia.augmentation as K
from kornia.augmentation import AugmentationSequential

torch.manual_seed(42)
x = torch.rand(2, 3, 6, 8)
g = torch.Generator().manual_seed(1234)

# 1. no constructor takes one
for build in (lambda: K.RandomAffine(degrees=(45.0, 45.0), p=1.0, generator=g),
              lambda: AugmentationSequential(K.RandomHorizontalFlip(p=1.0), generator=g)):
    try:
        build()
        print("constructor accepted generator=")
    except TypeError as e:
        print(f"constructor -> TypeError: {e}")

# 2. forward accepts it, ignores it, and says nothing
aug = K.RandomAffine(degrees=(0.0, 360.0), p=1.0)
torch.manual_seed(0)
a = aug(x, generator=torch.Generator().manual_seed(1))
angle_a = aug._params["angle"].tolist()
torch.manual_seed(0)
b = aug(x, generator=torch.Generator().manual_seed(2))
angle_b = aug._params["angle"].tolist()
print("forward(x, generator=...) returned:", tuple(a.shape))
print("  angles with generator seed 1:", angle_a)
print("  angles with generator seed 2:", angle_b)
print("  identical (the kwarg was dropped):", bool(torch.equal(a, b)))

# 3. the same swallow-anything path
print("forward(x, not_a_real_kwarg=1) :", tuple(aug(x, not_a_real_kwarg=1).shape))

# 4. what a caller is left with: the global stream, consumed by class-dependent amounts
for name, build in (("RandomHorizontalFlip p=1.0", lambda: K.RandomHorizontalFlip(p=1.0)),
                    ("RandomHorizontalFlip p=0.5", lambda: K.RandomHorizontalFlip(p=0.5)),
                    ("RandomAffine p=0.0", lambda: K.RandomAffine(degrees=(0.0, 360.0), p=0.0))):
    m = build()
    torch.manual_seed(0)
    m.forward_parameters(torch.Size((4, 3, 6, 8)))
    print(f"  global stream after {name:27s}: {torch.rand(1).item():.8f}")
torch.manual_seed(0)
print(f"  global stream with no augmentation at all : {torch.rand(1).item():.8f}")
```

## Observed

```
constructor -> TypeError: RandomAffine.__init__() got an unexpected keyword argument 'generator'
constructor -> TypeError: AugmentationSequential.__init__() got an unexpected keyword argument 'generator'
forward(x, generator=...) returned: (2, 3, 6, 8)
  angles with generator seed 1: [178.65237426757812, 276.5598449707031]
  angles with generator seed 2: [178.65237426757812, 276.5598449707031]
  identical (the kwarg was dropped): True
forward(x, not_a_real_kwarg=1) : (2, 3, 6, 8)
  global stream after RandomHorizontalFlip p=1.0 : 0.49625659
  global stream after RandomHorizontalFlip p=0.5 : 0.30742282
  global stream after RandomAffine p=0.0         : 0.30742282
  global stream with no augmentation at all : 0.49625659
```

`0.49625659` is the untouched-generator baseline: the flip at a static `p=1.0` consumes nothing at all, while `p=0.5` and `RandomAffine` at `p=0.0` each consume one draw. The per-class tally is in the batch's 84-class mechanical sweep (`class_sweep-output-cpu.txt`, rows `5.rng`): of the 67 classes it records a `p0_consumes` flag for, **47 consume global RNG even at `p=0.0`** and 20 do not.

## Expected

Two asks, and the second is the one that costs nothing to agree on:

1. **A per-instance generator.** `_BasicAugmentationBase.__init__` accepts `generator: Optional[torch.Generator] = None` and every sampler call threads it through, so a caller can isolate a pipeline's randomness the way `torch.rand(..., generator=g)` does. Keeping the default at `None` leaves every existing seeded script bitwise unchanged.
2. **`forward` rejects unknown keyword arguments**, naming the one it does not recognise, instead of accepting and discarding them. Today a caller who reaches for `generator=` — the natural guess — gets a silently seed-ignoring call, and the same path hides every keyword typo.

## Classification

**API completeness** — the per-stream randomness argument the rest of torch offers is absent, and the call that would ask for it is accepted and ignored rather than refused. Idiom: 3 (a guard whose predicate does not match the documented contract — here a kwarg path that validates nothing).

## Disposition

`n/a — single symbol`. Batch 6 documents the global-RNG contract and the swallow-unknown-kwargs behavior on the base anchor and pins the per-class consumption fingerprints, so a later change to sampling order is detectable. Both asks above are focused additions, welcome as PRs; the kwarg rejection turns silently-ignored calls into errors and is worth flagging in release notes.

## Environment

kornia 0.9.0rc1 @ `d6a2c138` (main), torch 2.14.0, python 3.11, cpu. Found during the augmentation conventions audit (batch 6, tracking issue #4407); the batch documents the behavior above as it is and pins it, and does not change it.

Posted on behalf of @ducha-aiki by Claude (Fable 5.1).
