### ISSUE TITLE
Usage of torch.solve is deprecated

### ISSUE THREAD

**Issue by polvoazul** [kornia/kornia#1223]
## 🐛 Bug (waiting to happen)

Kornia is using a deprecated function from torch, triggering this UserWarning below:

```
  ..../python3.9/site-packages/kornia/utils/helpers.py:96: UserWarning: torch.solve is deprecated in favor of torch.linalg.solveand will be removed in a future PyTorch release.
  torch.linalg.solve has its arguments reversed and does not return the LU factorization.
  To get the LU factorization see torch.lu, which can be used with torch.lu_solve or torch.lu_unpack.
  X = torch.solve(B, A).solution
  should be replaced with
  X = torch.linalg.solve(A, B) (Triggered internally at  /pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:760.)
```

We could substitute the line at `utils/helpers.py:96` from:
```
    out1, out2 = torch.solve(input.to(dtype), A.to(dtype))                                                                                                                                                 
to:
    out1 = torch.linalg.solve(A.to(dtype), input.to(dtype))
    out2 = ?
```
Unfortunatly the docs aren't explaining and I couldn't discover a way to get to out2, but then again, i have no experience with pytorch.                                                                                                                                      
 

## Environment

PyTorch version: 1.9.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.5 (default, May 18 2021, 19:34:48)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-25-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce MX230
Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.902
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.3.7.post0
[pip3] torch==1.9.0+cpu
[pip3] torchaudio==0.9.0
[pip3] torchmetrics==0.3.2
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0+cpu
[conda] Could not collect

**Comment by edgarriba** [comment]
@polvoazul thanks for reporting. Please, feel free to send a fixing PR - consider that we support PT 1.6 and `torch.linalg` I believe was introduced later than that.

**Comment by edgarriba** [comment]
solved in #1235

**Comment by smivv** [comment]
Still getting error:

```
    from kornia import affine, get_rotation_matrix2d, get_perspective_transform, \
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/__init__.py:13: in <module>
    from kornia import augmentation, color, contrib, enhance, feature, filters, geometry, jit, losses, morphology, utils
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/augmentation/__init__.py:1: in <module>
    from .augmentation import (
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/augmentation/augmentation.py:7: in <module>
    from kornia.augmentation.base import GeometricAugmentationBase2D, IntensityAugmentationBase2D, TensorWithTransformMat
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/augmentation/base.py:9: in <module>
    from kornia.utils.helpers import _torch_inverse_cast
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/utils/__init__.py:5: in <module>
    from .helpers import _extract_device_dtype
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/utils/helpers.py:5: in <module>
    from kornia.utils._compat import solve
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/utils/_compat.py:9: in <module>
    from torch.linalg import solve  # type: ignore
E   ImportError: cannot import name 'solve' from 'torch.linalg' (/home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages/torch/linalg/__init__.py)
```

torch==1.7.1+cpu
kornia==0.5.10

**Comment by edgarriba** [comment]
@smivv I just installed 1.7.1 and I'm not getting that error. Also check that we test against versions and all seems fine https://github.com/kornia/kornia/actions/runs/1189373964

could you report what your get from: `wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py`

Is it a fresh environment ?

**Comment by smivv** [comment]
Actually I am getting this from Github Actions while my local env works fine.

```
22s
Run python -m pip install --upgrade pip
Requirement already satisfied: pip in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (21.2.4)
Collecting pytest==6.1.2
  Using cached pytest-6.1.2-py3-none-any.whl (272 kB)
Requirement already satisfied: pytest-cov==2.10.1 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from -r tests/requirements.txt (line 2)) (2.10.1)
Requirement already satisfied: flake8==3.8.4 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from -r tests/requirements.txt (line 3)) (3.8.4)
Requirement already satisfied: faiss-cpu>=1.7.1 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from -r tests/requirements.txt (line 4)) (1.7.1.post2)
Collecting torch>=1.9.0
  Using cached torch-1.9.0-cp38-cp38-manylinux1_x86_64.whl (831.4 MB)
Collecting kornia==0.5.10
  Using cached kornia-0.5.10-py2.py3-none-any.whl (309 kB)
Requirement already satisfied: pluggy<1.0,>=0.12 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from pytest==6.1.2->-r tests/requirements.txt (line 1)) (0.13.1)
Requirement already satisfied: toml in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from pytest==6.1.2->-r tests/requirements.txt (line 1)) (0.10.2)
Requirement already satisfied: attrs>=17.4.0 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from pytest==6.1.2->-r tests/requirements.txt (line 1)) (20.3.0)
Requirement already satisfied: packaging in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from pytest==6.1.2->-r tests/requirements.txt (line 1)) (20.9)
Requirement already satisfied: iniconfig in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from pytest==6.1.2->-r tests/requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: py>=1.8.2 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from pytest==6.1.2->-r tests/requirements.txt (line 1)) (1.10.0)
Requirement already satisfied: coverage>=4.4 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from pytest-cov==2.10.1->-r tests/requirements.txt (line 2)) (5.5)
Requirement already satisfied: pycodestyle<2.7.0,>=2.6.0a1 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from flake8==3.8.4->-r tests/requirements.txt (line 3)) (2.6.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from flake8==3.8.4->-r tests/requirements.txt (line 3)) (0.6.1)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from flake8==3.8.4->-r tests/requirements.txt (line 3)) (2.2.0)
Requirement already satisfied: typing-extensions in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from torch>=1.9.0->-r tests/requirements.txt (line 5)) (3.7.4.3)
Requirement already satisfied: pyparsing>=2.0.2 in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from packaging->pytest==6.1.2->-r tests/requirements.txt (line 1)) (2.4.7)
Installing collected packages: torch, pytest, kornia
  Attempting uninstall: torch
    Found existing installation: torch 1.7.1+cpu
    Uninstalling torch-1.7.1+cpu:
      Successfully uninstalled torch-1.7.1+cpu
  Attempting uninstall: pytest
    Found existing installation: pytest 5.1.3
    Uninstalling pytest-5.1.3:
      Successfully uninstalled pytest-5.1.3
  Attempting uninstall: kornia
    Found existing installation: kornia 0.4.1
    Uninstalling kornia-0.4.1:
      Successfully uninstalled kornia-0.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
Successfully installed kornia-0.5.10 pytest-6.1.2 torch-1.9.0
torchvision 0.8.2 requires torch==1.7.1, but you have torch 1.9.0 which is incompatible.
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.7.1+cpu
  Using cached https://download.pytorch.org/whl/cpu/torch-1.7.1%2Bcpu-cp38-cp38-linux_x86_64.whl (159.4 MB)
Requirement already satisfied: numpy in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from torch==1.7.1+cpu) (1.20.1)
Requirement already satisfied: typing-extensions in /home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages (from torch==1.7.1+cpu) (3.7.4.3)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 1.9.0
    Uninstalling torch-1.9.0:
      Successfully uninstalled torch-1.9.0
Successfully installed torch-1.7.1+cpu
```


```
Run pytest
============================= test session starts ==============================
platform linux -- Python 3.8.9, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/actions-runner-oniwa/actions-runner/_work/oniwa/oniwa, configfile: setup.cfg, testpaths: tests
plugins: logger-0.5.1, cov-2.10.1
collected 678 items / 1 error / 677 selected

==================================== ERRORS ====================================
___________ ERROR collecting tests/cv/transforms/test_transforms.py ____________
ImportError while importing test module '/home/actions-runner-oniwa/actions-runner/_work/oniwa/oniwa/tests/cv/transforms/test_transforms.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../_tool/Python/3.8.9/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/cv/transforms/test_transforms.py:7: in <module>
    from oniwa.cv.transforms.batchwise import (
oniwa/cv/transforms/__init__.py:1: in <module>
    from oniwa.cv.transforms.batchwise import (
oniwa/cv/transforms/batchwise/__init__.py:1: in <module>
    from oniwa.cv.transforms.batchwise.affine import Perspective, ShiftScaleRotate
oniwa/cv/transforms/batchwise/affine.py:5: in <module>
    from kornia import affine, get_rotation_matrix2d, get_perspective_transform, \
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/__init__.py:13: in <module>
    from kornia import augmentation, color, contrib, enhance, feature, filters, geometry, jit, losses, morphology, utils
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/augmentation/__init__.py:1: in <module>
    from .augmentation import (
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/augmentation/augmentation.py:7: in <module>
    from kornia.augmentation.base import GeometricAugmentationBase2D, IntensityAugmentationBase2D, TensorWithTransformMat
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/augmentation/base.py:9: in <module>
    from kornia.utils.helpers import _torch_inverse_cast
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/utils/__init__.py:5: in <module>
    from .helpers import _extract_device_dtype
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/utils/helpers.py:5: in <module>
    from kornia.utils._compat import solve
../../_tool/Python/3.8.9/x64/lib/python3.8/site-packages/kornia/utils/_compat.py:9: in <module>
    from torch.linalg import solve  # type: ignore
E   ImportError: cannot import name 'solve' from 'torch.linalg' (/home/actions-runner-oniwa/actions-runner/_work/_tool/Python/3.8.9/x64/lib/python3.8/site-packages/torch/linalg/__init__.py)
```

**Comment by edgarriba** [comment]
I parse an error from pip resolver in your log - is it possible to try with conda ?

**Comment by edgarriba** [comment]
Is it a requirement for you 1.7.1 ? Seems due to torchvision version too

**Comment by smivv** [comment]
I've changed github.actions requirements to torch==1.8.0 and now it works.
The only problem is that it should work with 1.7.1, but it does not 😃

**Comment by edgarriba** [comment]
Happy to hear that. That's weird that only happens in GH actions. Maybe the version cashing is not well resolved.
