### ISSUE TITLE
Kornia to numpy error

### ISSUE THREAD

**Issue by GiannisApost** [kornia/kornia#3122]
### Describe the bug

I am trying to convert kornia to numpy exactly as shown in the example in the documentation page. However it shows this error when i run it 

Traceback (most recent call last):                                                                                                       
  File "/home/jovyan/work/try_numpy_kornia.py", line 19, in <module>
    gray_image = np_kornia.color.rgb_to_grayscale(rgb_image)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/main.py", line 375, in wrapper
    callable_obj = transpile(
                   ^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/main.py", line 772, in transpile
    return translate(
           ^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/main.py", line 725, in translate
    raise e
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/main.py", line 708, in translate
    translated_object = translators_container.run_translators(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/translators_container.py", line 54, in run_translators
    object = translator.translate(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/translations/translator.py", line 406, in translate
    self._standard_translate(object_like, reuse_existing=reuse_existing)
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/translations/translator.py", line 197, in _standard_translate
    _ = Translator.simple_translate(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/translations/translator.py", line 313, in simple_translate
    ast_root = ast_transformer.transform(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 185, in transform
    self._apply(
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 150, in _apply
    t.transform()
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 89, in transform
    self.visit(self.root)
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 483, in generic_visit
    value = self.visit(value)
            ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 596, in visit_FunctionDef
    self.visit(item)
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 676, in visit_Attribute
    node = self._handle_name_or_attribute(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 332, in _handle_name_or_attribute
    return self._maybe_recursively_translate(orig_obj, name_str, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 285, in _maybe_recursively_translate
    return self._recursively_translate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 236, in _recursively_translate
    _ = Translator.simple_translate(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/translations/translator.py", line 313, in simple_translate
    ast_root = ast_transformer.transform(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 185, in transform
    self._apply(
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 150, in _apply
    t.transform()
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 89, in transform
    self.visit(self.root)
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 483, in generic_visit
    value = self.visit(value)
            ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 596, in visit_FunctionDef
    self.visit(item)
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 676, in visit_Attribute
    node = self._handle_name_or_attribute(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 332, in _handle_name_or_attribute
    return self._maybe_recursively_translate(orig_obj, name_str, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 285, in _maybe_recursively_translate
    return self._recursively_translate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 236, in _recursively_translate
    _ = Translator.simple_translate(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/translations/translator.py", line 313, in simple_translate
    ast_root = ast_transformer.transform(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 185, in transform
    self._apply(
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 150, in _apply
    t.transform()
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 89, in transform
    self.visit(self.root)
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 483, in generic_visit
    value = self.visit(value)
            ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 596, in visit_FunctionDef
    self.visit(item)
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 483, in generic_visit
    value = self.visit(value)
            ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 676, in visit_Attribute
    node = self._handle_name_or_attribute(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 332, in _handle_name_or_attribute
    return self._maybe_recursively_translate(orig_obj, name_str, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 285, in _maybe_recursively_translate
    return self._recursively_translate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 236, in _recursively_translate
    _ = Translator.simple_translate(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/translations/translator.py", line 313, in simple_translate
    ast_root = ast_transformer.transform(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 185, in transform
    self._apply(
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 150, in _apply
    t.transform()
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 89, in transform
    self.visit(self.root)
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 483, in generic_visit
    value = self.visit(value)
            ^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 596, in visit_FunctionDef
    self.visit(item)
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/base_transformer.py", line 17, in visit
    result = super().visit(node)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 671, in visit_Name
    node = self._handle_name_or_attribute(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 332, in _handle_name_or_attribute
    return self._maybe_recursively_translate(orig_obj, name_str, node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 285, in _maybe_recursively_translate
    return self._recursively_translate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformers/recursive_transformer/base_transformer.py", line 236, in _recursively_translate
    _ = Translator.simple_translate(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/translations/translator.py", line 313, in simple_translate
    ast_root = ast_transformer.transform(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 185, in transform
    self._apply(
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/transformations/transformer.py", line 151, in _apply
    self.logger.log_transformed_code(
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/utils/logging_utils.py", line 228, in log_transformed_code
    source_code = ast_to_source_code(ast_node)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/ivy/transpiler/utils/ast_utils.py", line 1040, in ast_to_source_code
    ast_node = gast.gast_to_ast(ast_node)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/gast/ast3.py", line 514, in gast_to_ast
    return GAstToAst3().visit(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/gast/astn.py", line 26, in generic_visit
    setattr(new_node, field, self._visit(getattr(node, field)))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/gast/astn.py", line 13, in _visit
    return [self._visit(n) for n in node]
            ^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/gast/astn.py", line 11, in _visit
    return self.visit(node)
           ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/ast.py", line 407, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "/opt/conda/envs/testingenv/lib/python3.12/site-packages/gast/astn.py", line 26, in generic_visit
    setattr(new_node, field, self._visit(getattr(node, field)))
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClassDef' object has no attribute 'type_params'

### Reproduction steps

```bash
Run the kornia to numpy example: 

import kornia
import numpy as np

np_kornia = kornia.to_numpy()

rgb_image = np.random.normal(size=(1, 3, 224, 224))
gray_image = np_kornia.color.rgb_to_grayscale(rgb_image)
```

### Expected behavior

The input image converted to grayscale

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

- PyTorch Version (e.g., 1.0): 2.6.0
- OS (e.g., Linux): linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.12.0
- CUDA/cuDNN version: 12.2
- GPU models and configuration: rtx 3090
- Any other relevant information:
```

**Comment by edgarriba** [comment]
what version of `ivy` do you have ? @Sam-Armstrong

**Comment by GiannisApost** [comment]
I have the latest one Version: 1.0.0.3

**Comment by Sam-Armstrong** [comment]
@GiannisApost This is a bit of a strange one, basically the latest version of [gast](https://pypi.org/project/gast/0.6.0/#history) does not seem to work correctly with python 3.12 and up. However, the issue is fixed if you downgrade the gast version to 0.5.4 or lower. I'm not exactly sure why this is happening, so I'll dive into this deeper, but for a quick fix just do `pip install gast==0.5.4` and hopefully it should work fine. For now I've [pinned](https://github.com/ivy-llc/ivy/commit/fc61fcbd6b5df0ff05f34ac56d0e6c2f5dcce2e2) the gast version in the ivy requirements.

**Comment by GiannisApost** [comment]
@Sam-Armstrong Indeed downgrading gast version to 0.5.4 fixed it for me as well.

**Comment by Sam-Armstrong** [comment]
@GiannisApost this should be fixed now for the latest gast versions with the ivy 1.0.04 release
